In [34]:
import pandas as pd
import numpy as np

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


In [36]:
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
df= pd.read_csv("data.csv")

In [38]:
df.head()

class                                           comments
0      1                              you are sick upstairs
1      0  i really dont understand your pointxa0 it seem...
2      0  axcxa0majority of canadians can and has been w...
3      0  sdl ok but i would hope theyd sign him to a on...
4      0                         yeah and where are you now

In [39]:
df.size

8744

In [40]:
df.columns

Index(['class', 'comments'], dtype='object')

In [41]:
#checking for datatypes
df.dtypes

class        int64
comments    object
dtype: object

In [42]:
#checking for missing nan
df.isnull().isnull().sum()

class       0
comments    0
dtype: int64

In [43]:
df_data = df[["class", "comments"]]

In [44]:
df_data.columns

Index(['class', 'comments'], dtype='object')

In [45]:
df_x = df_data["comments"]
df_y = df_data["class"]

In [46]:
#Feature Extraction from Text

cv = CountVectorizer()
ex = cv.fit_transform(["Hello baby gitl", "My Nigga wetin dey"])

In [47]:
ex.toarray()

array([[1, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1, 1]])

In [48]:
cv.get_feature_names()

['baby', 'dey', 'gitl', 'hello', 'my', 'nigga', 'wetin']

In [49]:
corpus = df_x
cv = CountVectorizer()
X = cv.fit_transform(corpus)

In [50]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
cv.get_feature_names()

['00',
 '000',
 '0000',
 '00000',
 '000000',
 '0000harrison',
 '0001nobama',
 '000nnjfeigelsondebevoisecomnnnnnnall',
 '000sxcxa0',
 '001',
 '0011',
 '00gallonxcxa0',
 '00nnemmanueltouheythehillcomnnnnand',
 '00nnthis',
 '00xa0',
 '00xa0islam',
 '01',
 '010',
 '010nndid',
 '010nnthe',
 '010xcxa0maxine',
 '011',
 '011nnthe',
 '01it',
 '01nnnndear',
 '01nthe',
 '01skeeter',
 '0bama',
 '0bstructionism',
 '0f',
 '0fps',
 '0k',
 '0kg',
 '0ld',
 '0nndallas',
 '0nokc',
 '0nsee',
 '0px',
 '0pxparam',
 '0s',
 '0th',
 '0thcentury',
 '0you',
 '10',
 '100',
 '1000',
 '10000',
 '100000',
 '100k',
 '100nthey',
 '100st',
 '100sxa0',
 '101',
 '1011',
 '10110',
 '10k',
 '10lbs',
 '10mp',
 '10nceltics',
 '10nnwhat',
 '10pm',
 '10s',
 '10snnn',
 '10th',
 '10x',
 '10xa0',
 '10xa0ncountries',
 '11',
 '11010',
 '110111',
 '11despite',
 '11nspurs',
 '11th',
 '1500',
 '16',
 '17',
 '18',
 '1976',
 '19800',
 '1am',
 '1bpblogspotcomyvszmvvirwtmokfaugmiaaaaaaaaa0knllaahknniss100kill',
 '1cm',
 '1htmlxcxa0nnfor',

In [52]:
#model Building

from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, df_y, test_size=0.3, random_state=42)

In [54]:
X_train

<3060x18923 sparse matrix of type '<class 'numpy.int64'>'
	with 71327 stored elements in Compressed Sparse Row format>

In [55]:
#logistic Regression 81%

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8147865853658537

In [56]:
# #naive bayes 77%

# from sklearn.naive_bayes import MultinomialNB
# clf = MultinomialNB()
# clf.fit(X_train, y_train)
# clf.score(X_test, y_test)

In [57]:
clf.predict(X_test)

array([1, 1, 0, ..., 0, 0, 0])

In [58]:
#sample prediction
comment = ['Hello fine boy']
vect = cv.transform(comment).toarray() 

In [59]:
clf.predict(vect)

array([0])

In [60]:
if clf.predict(vect) == 1:
    print("Hate Sppech")
else:
    print("Not Hate Speech")

Not Hate Speech


In [61]:
#sample prediction 2
comment2 = ['fuck you nigga']
vect2 = cv.transform(comment2).toarray()
clf.predict(vect2)

array([1])

In [62]:
import pickle

In [63]:
logisticML = open("myFinalModel.pkl", "wb")

In [64]:
pickle.dump(clf, logisticML)

In [65]:
logisticML.close()

In [66]:


#load the model
my_model = open("myFinalModel.pkl", "rb")
new_model = pickle.load(my_model)